name: "Lint and Test Charts"

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-test:
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup Go"
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: "Setup Helm"
        uses: azure/setup-helm@v3
        with:
          version: "v3.10.3"

      - name: "Setup helm-docs"
        run: |
          HELM_DOCS_VERSION="1.11.0"
          OS=$(uname)
          curl -sSfL https://github.com/norwoodj/helm-docs/releases/download/v"${HELM_DOCS_VERSION}"/helm-docs_"${HELM_DOCS_VERSION}"_${OS}_x86_64.tar.gz \
            | tar zx -C /tmp
          sudo mv /tmp/helm-docs /usr/local/bin

      - name: "Run helm-docs"
        run: helm-docs && git diff --no-patch --exit-code

      - name: "Set up chart-testing"
        uses: helm/chart-testing-action@v2.3.1

      - name: "Run chart-testing (lint)"
        run: ct lint --config ct.yaml

      - name: "Setup kind"
        run: |
          make -C e2e setup
          make -C e2e init-cluster

      - name: "Run chart-testing (install)"
        run: ct install --config ct.yaml
