name: "Lint and Test Charts"

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-test:
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: "Setup Tools"
        run: |
          make setup

      - name: "Run helm-docs"
        run: ./bin/helm-docs && git diff --no-patch --exit-code

      - name: "Set up chart-testing"
        uses: helm/chart-testing-action@v2.6.1

      - name: "Run chart-testing (lint)"
        run: ct lint --config ct.yaml

      - name: "Setup kind"
        run: |
          make -C e2e setup
          make -C e2e init-cluster

      - name: "Run chart-testing (install)"
        run: ct install --config ct.yaml
